apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
  namespace: ilia-lab7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: web
        image: temnitsa/lab7-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        # Даем Джаве чуть больше времени на старт
        startupProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  namespace: ilia-lab7
spec:
  selector:
    app: petclinic
  ports:
    - protocol: TCP
      port: 80           # Вход из интернета
      targetPort: 8080   # Вход в контейнер
  type: LoadBalancer
