apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab7-deployment
  namespace: ilia-lab7  # Твой namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab7
  template:
    metadata:
      labels:
        app: lab7
    spec:
      containers:
      - name: java-app
        image: temnitsa/lab7-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: lab7-loadbalancer
  namespace: ilia-lab7  # Твой namespace
spec:
  selector:
    app: lab7
  type: LoadBalancer    # Внешний IP от Яндекса
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

